Friendships
RadiactiveJesus/rails-final-project pull request #4
Opened 2020-02-04 13:00 UTC by RadiactiveJesus

2020-02-04 16:51 UTC, imhta requested changes
# Changes required 🛑 

### Hello  @RadiactiveJesus  , 👋 You have done a great job in this project 👏 
> It seems you are working alone, Did you inform it to student success team? If not kindly inform
* [ ] Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) 
* [ ] db migration, throws error fix that
![image](https://user-images.githubusercontent.com/25448577/73766892-b546ae80-479c-11ea-802f-7f1a7af38d7d.png)

----
### Don't forget to request another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

2020-02-06 16:19 UTC, RadiactiveJesus commented
> # Changes required 🛑
> ### Hello @RadiactiveJesus , 👋 You have done a great job in this project 👏
> > It seems you are working alone, Did you inform it to student success team? If not kindly inform
> 
> * [ ]  Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
> * [ ]  db migration, throws error fix that
>   ![image](https://user-images.githubusercontent.com/25448577/73766892-b546ae80-479c-11ea-802f-7f1a7af38d7d.png)
> 
> ### Don't forget to request another code review
> **Pon Muthu Selvam N**
> **[nponmuthuselvam@gmail.com](mailto:nponmuthuselvam@gmail.com)**
> _If you have any queries, feel free to ping me on slack_

Hello, yes Im working alone on the final Rails Project, student success is already informed about the situation. Thanks, on the other hand, ye  I willtake care of the description of the pull request

2020-02-06 20:11 UTC, maelfosso requested changes
# Changes required

Hello @RadiactiveJesus 

From the console, the friendship is OK. However, there are two errors that happens.
The first one was after accepting the friendship request, I click on `Home` link and I got this error
![Screenshot_2020-02-06_15-04-14](https://user-images.githubusercontent.com/8848104/73974476-69a61900-48f2-11ea-9039-9f95fb272165.png)

Before that, I tried to access to an url and I got this error
![Screenshot_2020-02-06_15-01-37](https://user-images.githubusercontent.com/8848104/73974533-788ccb80-48f2-11ea-91e9-0f9a33f86a74.png)

Also, please take a look on the comment below. The posts concern only the current user post's and his friend's post.

Kindly make the suggested changes and fixed the bug and then submit a new code review request.
Don't hesitate to write me on Slack if you have any problem.

Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2020-02-07 03:00 UTC, maelfosso commented on facebook/app/controllers/home_controller.rb
> +    @posts = Post.all
Here, things should change. You must no longer take all the posts but only created by the current user or by his friends

2020-02-12 21:47 UTC, wathigo approved these changes
### Approved :heavy_check_mark: 
Great work implementing the requested changes.

**You may move on.**

**Good luck :four_leaf_clover: 
Simon Wathigo**

2020-02-26 12:52 UTC, merged